{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\li360\ri0\sa50\partightenfactor0

\f0\fs19 \cf0 FROM debian:wheezy\
RUN apt-get update && apt-get install -y cowsay fortune}