{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fmodern\fcharset0 CourierNewPSMT;\f1\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\li360\ri0\sa50\partightenfactor0

\f0\fs20 \cf0 FROM vkohli/devbase
\f1\fs19 \

\f0\fs20 RUN apt-get update
\f1\fs19 \

\f0\fs20 RUN apt-get -y install ruby1.8 git ruby1.8-dev}